export const EDITOR_TEXT = {
    en: {
        cropButton: 'Crop',
        filterButton: 'Filter',
        colorsButton: 'Colors',
        cancelButton: 'Cancel',
        doneButton: 'Done',
        sliderBrightness: 'Brightness',
        sliderContrast: 'Contrast',
        sliderSaturation: 'Saturation',
        flipHorizontal: 'Flip horizontal',
        flipVertical: 'Flip vertical',
        noFilter: 'No Filter',
        filters: {
            "Horizontal Lines": "horizontal_lines",
            "Extreme Offset Blue": "extreme_offset_blue",
            "Ocean": "ocean",
            "Extreme Offset Green": "extreme_offset_green",
            "Offset Green": "offset_green",
            "Extra Offset Blue": "extra_offset_blue",
            "Extra Offset Red": "extra_offset_red",
            "Extra Offset Green": "extra_offset_green",
            "Extreme Offset Red": "extreme_offset_red",
            "Specks Redscale": "specks_redscale",
            "Vintage": "vintage",
            "Perfume": "perfume",
            "Serenity": "serenity",
            "Eclectic": "eclectic",
            "Diagonal Lines": "diagonal_lines",
            "Green Specks": "green_specks",
            "Warmth": "warmth",
            "Casino": "casino",
            "Green Diagonal Lines": "green_diagonal_lines",
            "Offset": "offset",
            "Offset Blue": "offset_blue",
            "Neue": "neue",
            "Sunset": "sunset",
            "Specks": "specks",
            "Wood": "wood",
            "Lix": "lix",
            "Ryo": "ryo",
            "Bluescale": "bluescale",
            "Solange": "solange",
            "Evening": "evening",
            "Crimson": "crimson",
            "Teal Min Noise": "teal_min_noise",
            "Phase": "phase",
            "Dark Purple Min Noise": "dark_purple_min_noise",
            "Coral": "coral",
            "Darkify": "darkify",
            "Brightness": "incbrightness",
            "Brightness Second": "incbrightness2",
            "Yellow Casino": "yellow_casino",
            "Invert": "invert",
            "Saturation": "sat_adj",
            "Lemon": "lemon",
            "Pink Min Noise": "pink_min_noise",
            "Frontward": "frontward",
            "Pink Aura": "pink_aura",
            "Haze": "haze",
            "Cool Twilight": "cool_twilight",
            "Blues": "blues",
            "Mellow": "mellow",
            "Solange Dark": "solange_dark",
            "Solange Grey": "solange_grey",
            "Zapt": "zapt",
            "Eon": "eon",
            "Aeon": "aeon",
            "Matrix": "matrix",
            "Cosmic": "cosmic",
            "Min Noise": "min_noise",
            "Red Min Noise": "red_min_noise",
            "Matrix2": "matrix2",
            "Purplescale": "purplescale",
            "Radio": "radio",
            "Twenties": "twenties",
            "Pixel Blue": "pixel_blue",
            "Greyscale": "greyscale",
            "Grime": "grime",
            "Red Greyscale": "redgreyscale",
            "Retroviolet": "retroviolet",
            "Greengreyscale": "greengreyscale",
            "Green Med Noise": "green_med_noise",
            "Green Min Noise": "green_min_noise",
            "Blue Min Noise": "blue_min_noise",
            "Rosetint": "rosetint",
            "Purple Min Noise": "purple_min_noise",
            "Red Effect": "red_effect",
            "Gamma": "gamma",
            "Teal Gamma": "teal_gamma",
            "Purple Gamma": "purple_gamma",
            "Yellow Gamma": "yellow_gamma",
            "Bluered Gamma": "bluered_gamma",
            "Green Gamma": "green_gamma",
            "Red Gamma": "red_gamma",
            "Black Specks": "black_specks",
            "White Specks": "white_specks",
            "Salt and Pepper": "salt_and_pepper",
            "RGB Split": "rgbSplit",
            "Threshold": "threshold",
            "Threshold 75": "threshold75",
            "Threshold 125": "threshold125",
            "Pixelate": "pixelate",
            "Pixelate 16": "pixelate16"
        }
    },
    es: {
        cropButton: 'Recortar',
        filterButton: 'Filtro',
        colorsButton: 'Colores',
        cancelButton: 'Cancelar',
        doneButton: 'Listo',
        sliderBrightness: 'Brillo',
        sliderContrast: 'Contraste',
        sliderSaturation: 'Saturación',
        flipHorizontal: 'Voltear horizontalmente',
        flipVertical: 'Voltear verticalmente',
        noFilter: 'Sin filtro',
        filters: {
            "Líneas Horizontales": "horizontal_lines",
            "Azul Extremo Desplazado": "extreme_offset_blue",
            "Océano": "ocean",
            "Verde Extremo Desplazado": "extreme_offset_green",
            "Verde Desplazado": "offset_green",
            "Azul Extra Desplazado": "extra_offset_blue",
            "Rojo Extra Desplazado": "extra_offset_red",
            "Verde Extra Desplazado": "extra_offset_green",
            "Rojo Extremo Desplazado": "extreme_offset_red",
            "Efecto Manchas Rojas": "specks_redscale",
            "Vintage": "vintage",
            "Perfume": "perfume",
            "Serenidad": "serenity",
            "Ecléctico": "eclectic",
            "Líneas Diagonales": "diagonal_lines",
            "Manchas Verdes": "green_specks",
            "Calidez": "warmth",
            "Casino": "casino",
            "Líneas Diagonales Verdes": "green_diagonal_lines",
            "Desplazado": "offset",
            "Azul Desplazado": "offset_blue",
            "Neue": "neue",
            "Atardecer": "sunset",
            "Manchas": "specks",
            "Madera": "wood",
            "Lix": "lix",
            "Ryo": "ryo",
            "Escala Azul": "bluescale",
            "Solange": "solange",
            "Noche": "evening",
            "Carmesí": "crimson",
            "Ruido Mínimo Teal": "teal_min_noise",
            "Fase": "phase",
            "Ruido Mínimo Morado Oscuro": "dark_purple_min_noise",
            "Coral": "coral",
            "Oscurecer": "darkify",
            "Brillo": "incbrightness",
            "Segundo Brillo": "incbrightness2",
            "Casino Amarillo": "yellow_casino",
            "Invertir": "invert",
            "Saturación": "sat_adj",
            "Limón": "lemon",
            "Ruido Mínimo Rosa": "pink_min_noise",
            "Hacia Adelante": "frontward",
            "Aura Rosa": "pink_aura",
            "Neblina": "haze",
            "Anochecer Fresco": "cool_twilight",
            "Azules": "blues",
            "Suave": "mellow",
            "Solange Oscuro": "solange_dark",
            "Solange Gris": "solange_grey",
            "Zapt": "zapt",
            "Eon": "eon",
            "Aeon": "aeon",
            "Matriz": "matrix",
            "Cósmico": "cosmic",
            "Ruido Mínimo": "min_noise",
            "Ruido Mínimo Rojo": "red_min_noise",
            "Matriz2": "matrix2",
            "Escala Morada": "purplescale",
            "Radio": "radio",
            "Años Veinte": "twenties",
            "Azul Pixelado": "pixel_blue",
            "Escala de Grises": "greyscale",
            "Suciedad": "grime",
            "Escala de Grises Roja": "redgreyscale",
            "Retrovioleta": "retroviolet",
            "Escala de Grises Verde": "greengreyscale",
            "Ruido Medio Verde": "green_med_noise",
            "Ruido Mínimo Verde": "green_min_noise",
            "Ruido Mínimo Azul": "blue_min_noise",
            "Tinte Rosa": "rosetint",
            "Ruido Mínimo Morado": "purple_min_noise",
            "Efecto Rojo": "red_effect",
            "Gamma": "gamma",
            "Gamma Teal": "teal_gamma",
            "Gamma Morado": "purple_gamma",
            "Gamma Amarillo": "yellow_gamma",
            "Gamma Azul-Rojo": "bluered_gamma",
            "Gamma Verde": "green_gamma",
            "Gamma Rojo": "red_gamma",
            "Manchas Negras": "black_specks",
            "Manchas Blancas": "white_specks",
            "Sal y Pimienta": "salt_and_pepper",
            "Separación RGB": "rgbSplit",
            "Umbral": "threshold",
            "Umbral 75": "threshold75",
            "Umbral 125": "threshold125",
            "Pixelado": "pixelate",
            "Pixelado 16": "pixelate16"
        }
    },
    zh: {
        cropButton: '裁剪',
        filterButton: '滤镜',
        colorsButton: '颜色',
        cancelButton: '取消',
        doneButton: '完成',
        sliderBrightness: '亮度',
        sliderContrast: '对比度',
        sliderSaturation: '饱和度',
        flipHorizontal: '水平翻转',
        flipVertical: '垂直翻转',
        noFilter: '无滤镜',
        filters: {
            "水平线": "horizontal_lines",
            "极端偏移蓝色": "extreme_offset_blue",
            "海洋": "ocean",
            "极端偏移绿色": "extreme_offset_green",
            "偏移绿色": "offset_green",
            "额外偏移蓝色": "extra_offset_blue",
            "额外偏移红色": "extra_offset_red",
            "额外偏移绿色": "extra_offset_green",
            "极端偏移红色": "extreme_offset_red",
            "斑点红色": "specks_redscale",
            "复古": "vintage",
            "香水": "perfume",
            "宁静": "serenity",
            "折衷": "eclectic",
            "对角线": "diagonal_lines",
            "绿斑点": "green_specks",
            "温暖": "warmth",
            "赌场": "casino",
            "绿色对角线": "green_diagonal_lines",
            "偏移": "offset",
            "偏移蓝色": "offset_blue",
            "新": "neue",
            "日落": "sunset",
            "斑点": "specks",
            "木材": "wood",
            "蜡": "lix",
            "瑞奥": "ryo",
            "蓝调": "blues",
            "索兰吉": "solange",
            "傍晚": "evening",
            "深红": "crimson",
            "青绿最小噪音": "teal_min_noise",
            "阶段": "phase",
            "深紫色最小噪音": "dark_purple_min_noise",
            "珊瑚": "coral",
            "变暗": "darkify",
            "亮度": "incbrightness",
            "亮度第二": "incbrightness2",
            "黄色赌场": "yellow_casino",
            "反转": "invert",
            "饱和度": "sat_adj",
            "柠檬": "lemon",
            "粉色最小噪音": "pink_min_noise",
            "前进": "frontward",
            "粉色光环": "pink_aura",
            "阴霾": "haze",
            "酷傍晚": "cool_twilight",
            "温和": "mellow",
            "索兰吉黑": "solange_dark",
            "索兰吉灰": "solange_grey",
            "扎普特": "zapt",
            "永恒": "eon",
            "时光矩阵": "aeon",
            "宇宙的": "cosmic",
            "最小噪音": "min_noise",
            "红色最小噪音": "red_min_noise",
            "矩阵2": "matrix2",
            "紫红色调": "purplescale",
            "电台": "radio",
            "二十年代": "twenties",
            "像素蓝": "pixel_blue",
            "灰度": "greyscale",
            "污垢": "grime",
            "红色灰度": "redgreyscale",
            "复古紫色": "retroviolet",
            "绿色灰度": "greengreyscale",
            "绿色最小噪音": "green_min_noise",
            "蓝色最小噪音": "blue_min_noise",
            "玫瑰色调": "rosetint",
            "紫色最小噪音": "purple_min_noise",
            "红色效果": "red_effect",
            "伽马": "gamma",
            "青绿伽马": "teal_gamma",
            "紫色伽马": "purple_gamma",
            "黄色伽马": "yellow_gamma",
            "蓝红伽马": "bluered_gamma",
            "绿色伽马": "green_gamma",
            "红色伽马": "red_gamma",
            "黑斑点": "black_specks",
            "白斑点": "white_specks",
            "盐和胡椒": "salt_and_pepper",
            "RGB分离": "rgbSplit",
            "阈值": "threshold",
            "阈值 75": "threshold75",
            "阈值 125": "threshold125",
            "像素化": "pixelate",
            "像素化 16": "pixelate16"
        }
    },
    hin: {
        "cropButton": "कटाई करें",
        "filterButton": "फ़िल्टर",
        "colorsButton": "रंग",
        "cancelButton": "रद्द करें",
        "doneButton": "हो गया",
        "sliderBrightness": "चमक",
        "sliderContrast": "ताकत",
        "sliderSaturation": "रंगता",
        "flipHorizontal": "क्षैतिज उलटो",
        "flipVertical": "ऊर्ध्वाधर उलटो",
        "noFilter": "कोई फ़िल्टर नहीं",
        filters: {
            "क्षैतिज रेखाएं": "horizontal_lines",
            "अत्यधिक ऑफसेट नीला": "extreme_offset_blue",
            "महासागर": "ocean",
            "अत्यधिक ऑफसेट हरा": "extreme_offset_green",
            "ऑफसेट हरा": "offset_green",
            "अतिरिक्त ऑफसेट नीला": "extra_offset_blue",
            "अतिरिक्त ऑफसेट लाल": "extra_offset_red",
            "अतिरिक्त ऑफसेट हरा": "extra_offset_green",
            "अत्यधिक ऑफसेट लाल": "extreme_offset_red",
            "स्पेक रेडस्केल": "specks_redscale",
            "विंटेज": "vintage",
            "इत्र": "perfume",
            "शांति": "serenity",
            "एक्लेक्टिक": "eclectic",
            "विकर्ण रेखाएं": "diagonal_lines",
            "हरा स्पेक": "green_specks",
            "गर्माहट ": "warmth",
            "कैसीनो": "casino",
            "हरी विकर्ण रेखाएं": "green_diagonal_lines",
            "ऑफसेट": "offset",
            "ऑफसेट नीला": "offset_blue",
            "नीयू": "neue",
            "सूर्यास्त": "sunset",
            "स्पेक्स": "specks",
            "लकड़ी": "wood",
            "लिक्स": "lix",
            "रियो": "ryo",
            "ब्लूस्केल": "bluescale",
            "सोलेंज": "solange",
            "शाम": "evening",
            "क्रिमसन": "crimson",
            "चैती न्यूनतम शोर": "teal_min_noise",
            "चरण": "phase",
            "गहरा बैंगनी न्यूनतम शोर": "dark_purple_min_noise",
            "मूंगा": "coral",
            "अंधेरा": "darkify",
            "चमक": "incbrightness",
            "चमक दूसरा": "incbrightness2",
            "पीला कैसीनो": "yellow_casino",
            "उलटा": "invert",
            "संतृप्ति": "sat_adj",
            "नींबू": "lemon",
            "गुलाबी न्यूनतम शोर": "pink_min_noise",
            "सामने की ओर": "frontward",
            "गुलाबी आभा": "pink_aura",
            "धुंध": "haze",
            "ठंडा गोधूलि": "cool_twilight",
            "नीला": "blues",
            "मधुर": "mellow",
            "सोलेंज डार्क": "solange_dark",
            "सोलेंज ग्रे": "solange_grey",
            "जैप्ट": "zapt",
            "ईऑन": "eon",
            "एयॉन": "aeon",
            "मैट्रिक्स": "matrix",
            "कॉस्मिक": "cosmic",
            "न्यूनतम शोर": "min_noise",
            "लाल न्यूनतम नॉइज़": "red_min_noise",
            "मैट्रिक्स2": "matrix2",
            "पर्पलस्केल": "purplescale",
            "रेडियो": "radio",
            "ट्वेंटीज़": "twenties",
            "पिक्सेल ब्लू": "pixel_blue",
            "ग्रेस्केल": "greyscale",
            "ग्राइम": "grime",
            "रेड ग्रेस्केल": "redgreyscale",
            "रेट्रोवॉयलेट": "retroviolet",
            "ग्रीनग्रेस्केल": "greengreyscale",
            "ग्रीन मेड नॉइज़": "green_med_noise",
            "ग्रीन मिन नॉइज़": "green_min_noise",
            "ब्लू मिन नॉइज़": "blue_min_noise",
            "रोज़ेटिंट": "rosetint",
            "पर्पल मिन नॉइज़": "purple_min_noise",
            "रेड इफ़ेक्ट": "red_effect",
            "गामा": "gamma",
            "टील गामा": "teal_gamma",
            "बैंगनी गामा": "purple_gamma",
            "पीला गामा": "yellow_gamma",
            "नीला गामा": "bluered_gamma",
            "हरा गामा": "green_gamma",
            "लाल गामा": "red_gamma",
            "काले धब्बे": "black_specks",
            "सफेद धब्बे": "white_specks",
            "नमक और काली मिर्च": "salt_and_pepper",
            "आरजीबी स्प्लिट": "rgbSplit",
            "थ्रेशोल्ड": "threshold",
            "थ्रेशोल्ड 75": "threshold75",
            "थ्रेशोल्ड 125": "threshold125",
            "पिक्सलेट": "pixelate",
            "पिक्सलेट 16": "pixelate16"
        }
    },
    ja: {
        "cropButton": "切り取り",
        "filterButton": "フィルター",
        "colorsButton": "カラー",
        "cancelButton": "キャンセル",
        "doneButton": "完了",
        "sliderBrightness": "明るさ",
        "sliderContrast": "コントラスト",
        "sliderSaturation": "彩度",
        "flipHorizontal": "水平反転",
        "flipVertical": "垂直反転",
        "noFilter": "フィルターなし",
        filters: {
            "水平線": "horizontal_lines",
            "エクストリーム オフセット ブルー": "extreme_offset_blue",
            "オーシャン": "ocean",
            "エクストリーム オフセット グリーン": "extreme_offset_green",
            "オフセット グリーン": "offset_green",
            "エクストラ オフセット ブルー": "extra_offset_blue",
            "エクストラ オフセット レッド": "extra_offset_red",
            "エクストラ オフセット グリーン": "extra_offset_green",
            "エクストリーム オフセット レッド": "extreme_offset_red",
            "スペック レッドスケール": "specks_redscale",
            "ヴィンテージ": "vintage",
            "香水": "perfume",
            "静寂": "serenity",
            "折衷": "eclectic",
            "斜線": "diagonal_lines",
            "グリーンスペック": "green_specks",
            "暖かさ": "warmth",
            "カジノ": "casino",
            "緑色の斜線": "green_diagonal_lines",
            "オフセット": "offset",
            "オフセットブルー": "offset_blue",
            "ノイエ": "neue",
            "サンセット": "sunset",
            "斑点": "specks",
            "木": "wood",
            "リックス": "lix",
            "リョウ": "ryo",
            "ブルースケール": "bluescale",
            "ソランジュ": "solange",
            "イブニング": "evening",
            "クリムゾン": "crimson",
            "ティール最小ノイズ": "teal_min_noise",
            "フェーズ": "phase",
            "ダークパープル最小ノイズ": "dark_purple_min_noise",
            "コーラル": "coral",
            "暗化": "darkify",
            "明るさ": "incbrightness",
            "明るさセカンド": "incbrightness2",
            "イエローカジノ": "yellow_casino",
            "反転": "invert",
            "彩度": "sat_adj",
            "レモン": "lemon",
            "ピンクミンノイズ": "pink_min_noise",
            "前方": "frontward",
            "ピンクオーラ": "pink_aura",
            "ヘイズ": "haze",
            "クールトワイライト": "cool_twilight",
            "ブルース": "blues",
            "メロウ": "mellow",
            "ソランジュダーク": "solange_dark",
            "ソランジュグレー": "solange_grey",
            "ザプト": "zapt",
            "イオン": "aeon",
            "マトリックス": "matrix",
            "コズミック": "cosmic",
            "ミンノイズ": "min_noise",
            "レッドミンノイズ": "red_min_noise",
            "マトリックス2": "matrix2",
            "パープルスケール": "purplescale",
            "ラジオ": "radio",
            "20代": "twenties",
            "ピクセルブルー": "pixel_blue",
            "グレースケール": "greyscale",
            "グライム": "grime",
            "レッドグレースケール": "redgreyscale",
            "レトロバイオレット": "retroviolet",
            "グリーングレースケール": "greengreyscale",
            "グリーンメッドノイズ": "green_med_noise",
            "グリーン最小ノイズ": "green_min_noise",
            "ブルー最小ノイズ": "blue_min_noise",
            "ローゼティント": "rosetint",
            "パープル最小ノイズ": "purple_min_noise",
            "レッドエフェクト": "red_effect",
            "ガンマ": "gamma",
            "ティールガンマ": "teal_gamma",
            "紫ガンマ": "purple_gamma",
            "黄ガンマ": "yellow_gamma",
            "青赤ガンマ": "bluered_gamma",
            "緑ガンマ": "green_gamma",
            "赤ガンマ": "red_gamma",
            "黒斑点": "black_specks",
            "白斑点": "white_specks",
            "ソルト＆ペッパー": "salt_and_pepper",
            "RGB 分割": "rgbSplit",
            "しきい値": "threshold",
            "しきい値 75 ": "threshold75",
            "しきい値 125 ": "threshold125",
            "ピクセル化 ": "pixelate",
            "ピクセル化 16": "pixelate16"
        }
    },
    it: {
        "cropButton": "Taglia",
        "filterButton": "Filtro",
        "colorsButton": "Colori",
        "cancelButton": "Annulla",
        "doneButton": "Fatto",
        "sliderBrightness": "Luminosità",
        "sliderContrast": "Contrasto",
        "sliderSaturation": "Saturazione",
        "flipHorizontal": "Capovolgi orizzontalmente",
        "flipVertical": "Capovolgi verticalmente",
        "noFilter": "Nessun filtro",
        filters: {
            "Linee orizzontali": "horizontal_lines",
            "Blu offset estremo": "extreme_offset_blue",
            "Oceano": "ocean",
            "Verde offset estremo": "extreme_offset_green",
            "Verde offset": "offset_green",
            "Blu offset extra": "extra_offset_blue",
            "Rosso offset extra": "extra_offset_red",
            "Verde offset extra": "extra_offset_green",
            "Rosso offset estremo": "extreme_offset_red",
            "Scala rossa a granelli": "specks_redscale",
            "Vintage": "vintage",
            "Profumo": "perfume",
            "Serenità": "serenity",
            "Eclettico": "eclectic",
            "Linee diagonali": "diagonal_lines",
            "Macchie verdi": "green_specks",
            "Calore ": "warmth",
            "Casinò": "casino",
            "Linee diagonali verdi": "green_diagonal_lines",
            "Offset": "offset",
            "Offset Blu": "offset_blue",
            "Neue": "neue",
            "Tramonto": "sunset",
            "Macchie": "specks",
            "Legno": "wood",
            "Lix": "lix",
            "Ryo": "ryo",
            "Scala blu": "bluescale",
            "Solange": "solange",
            "Sera": "evening",
            "Cremisi": "crimson",
            "Alzavola Rumore minimo": "teal_min_noise",
            "Fase": "phase",
            "Rumore minimo viola scuro": "dark_purple_min_noise",
            "Corallo": "coral",
            "Darkify": "darkify",
            "Luminosità": "incbrightness",
            "Luminosità Secondo": "incbrightness2",
            "Casinò Giallo": "yellow_casino",
            "Inverti": "invert",
            "Saturazione": "sat_adj",
            "Limone": "lemon",
            "Rosa Rumore Min": "pink_min_noise",
            "In avanti": "frontward",
            "Aura Rosa": "pink_aura",
            "Foschia": "haze",
            "Crepuscolo Fresco": "cool_twilight",
            "Blues": "blues",
            "Molto": "mellow",
            "Solange Scuro": "solange_dark",
            "Grigio Solange": "solange_grey",
            "Zapt": "zapt",
            "Eon": "eon",
            "Aeon": "aeon",
            "Matrix": "matrix",
            "Cosmico": "cosmic",
            "Rumore Min": "min_noise",
            "Rosso Min Rumore": "red_min_noise",
            "Matrice2": "matrix2",
            "Scala viola": "purplescale",
            "Radio": "radio",
            "Anni '20": "twenties",
            "Pixel Blu": "pixel_blue",
            "Scala di grigi": "greyscale",
            "Sporco": "grime",
            "Scala di grigi rosso": "redgreyscale",
            "Retrovioletto": "retroviolet",
            "Scala di grigioverde": "greengreyscale",
            "Rumore medio verde": "green_med_noise",
            "Rumore minimo verde": "green_min_noise",
            "Rumore minimo blu": "blue_min_noise",
            "Rosentino": "rosetint",
            "Rumore minimo viola": "purple_min_noise",
            "Effetto rosso": "red_effect",
            "Gamma": "gamma",
            "Gamma verde acqua": "teal_gamma",
            "Gamma viola": "purple_gamma",
            "Gamma giallo": "yellow_gamma",
            "Gamma blu": "bluered_gamma",
            "Gamma verde": "green_gamma",
            "Gamma rosso": "red_gamma",
            "Macchi neri": "black_specks",
            "Macchi bianchi": "white_specks",
            "Sale e pepe": "salt_and_pepper",
            "Divisione RGB": "rgbSplit",
            "Soglia": "threshold",
            "Soglia 75": "threshold75",
            "Soglia 125": "threshold125",
            "Pixellato": "pixelate",
            "Pixellato 16": "pixelate16"
        }
    },
    fr: {
        "cropButton": "Recadrer",
        "filterButton": "Filtre",
        "colorsButton": "Couleurs",
        "cancelButton": "Annuler",
        "doneButton": "Terminé",
        "sliderBrightness": "Luminosité",
        "sliderContrast": "Contraste",
        "sliderSaturation": "Saturation",
        "flipHorizontal": "Retourner horizontalement",
        "flipVertical": "Retourner verticalement",
        "noFilter": "Pas de filtre",
        filters: {
            "Lignes horizontales": "horizontal_lines",
            "Bleu décalé extrême": "extreme_offset_blue",
            "Océan": "ocean",
            "Vert décalé extrême": "extreme_offset_green",
            "Vert décalé": "offset_green",
            "Bleu décalé supplémentaire": "extra_offset_blue",
            "Rouge décalé supplémentaire": "extra_offset_red",
            "Vert décalé supplémentaire": "extra_offset_green",
            "Rouge décalé extrême": "extreme_offset_red",
            "Échelle rouge de taches": "specks_redscale",
            "Vintage": "vintage",
            "Parfum": "perfume",
            "Sérénité": "serenity",
            "Éclectique": "eclectic",
            "Lignes diagonales": "diagonal_lines",
            "Points verts": "green_specks",
            "Chaleur ": "warmth",
            "Casino": "casino",
            "Lignes diagonales vertes": "green_diagonal_lines",
            "Décalage": "offset",
            "Décalage bleu": "offset_blue",
            "Neue": "neue",
            "Coucher de soleil": "sunset",
            "Points": "specks",
            "Bois": "wood",
            "Lix": "lix",
            "Ryo": "ryo",
            "Échelle bleue": "bluescale",
            "Solange": "solange",
            "Soirée": "evening",
            "Crimson": "crimson",
            "Sarcelle Min Bruit": "teal_min_noise",
            "Phase": "phase",
            "Violet foncé Min Bruit": "dark_purple_min_noise",
            "Corail": "coral",
            "Darkify": "darkify",
            "Luminosité": "incbrightness",
            "Luminosité Deuxièmement": "incbrightness2",
            "Yellow Casino": "yellow_casino",
            "Inverser": "invert",
            "Saturation": "sat_adj",
            "Citron": "lemon",
            "Bruit rose min": "pink_min_noise",
            "Frontward": "frontward",
            "Aura rose": "pink_aura",
            "Haze": "haze",
            "Crépuscule frais": "cool_twilight",
            "Blues": "blues",
            "Moelleux": "mellow",
            "Solange Dark": "solange_dark",
            "Solange Grey": "solange_grey",
            "Zapt": "zapt",
            "Eon": "eon",
            "Aeon": "aeon",
            "Matrix": "matrix",
            "Cosmic": "cosmic",
            "Min Noise": "min_noise",
            "Red Min Bruit": "red_min_noise",
            "Matrix2": "matrix2",
            "échelle de violet": "purplescale",
            "radio": "radio",
            "vingtaine": "twenties",
            "pixel bleu": "pixel_blue",
            "niveaux de gris": "greyscale",
            "crasse": "grime",
            "niveaux de gris rouges": "redgreyscale",
            "rétroviolet": "retroviolet",
            "niveaux de gris verts": "greengreyscale",
            "bruit vert moyen": "green_med_noise",
            "bruit minimum vert": "green_min_noise",
            "bruit minimum bleu": "blue_min_noise",
            "rosetinte": "rosetint",
            "bruit minimum violet": "purple_min_noise",
            "effet rouge": "red_effect",
            "Gamma": "gamma",
            "Gamma sarcelle": "teal_gamma",
            "Gamma violet": "purple_gamma",
            "Gamma jaune": "yellow_gamma",
            "Gamma bleuté": "bluered_gamma",
            "Gamma vert": "green_gamma",
            "Gamma rouge": "red_gamma",
            "Points noirs": "black_specks",
            "Points blancs": "white_specks",
            "Sel et poivre": "salt_and_pepper",
            "Split RVB": "rgbSplit",
            "Seuil": "threshold",
            "Seuil 75": "threshold75",
            "Seuil 125": "threshold125",
            "Pixelate": "pixelate",
            "Pixelate 16": "pixelate16"
        }
    }
}