export const EDITOR_TEXT = {
    en: {
        cropButton: 'Crop',
        filterButton: 'Filter',
        colorsButton: 'Colors',
        cancelButton: 'Cancel',
        doneButton: 'Done',
        sliderBrightness: 'Brightness',
        sliderContrast: 'Contrast',
        sliderSaturation: 'Saturation',
        flipHorizontal: 'Flip horizontal',
        flipVertical: 'Flip vertical',
        noFilter: 'No Filter',
        filters: {
            "Horizontal Lines": "horizontal_lines",
            "Extreme Offset Blue": "extreme_offset_blue",
            "Ocean": "ocean",
            "Extreme Offset Green": "extreme_offset_green",
            "Offset Green": "offset_green",
            "Extra Offset Blue": "extra_offset_blue",
            "Extra Offset Red": "extra_offset_red",
            "Extra Offset Green": "extra_offset_green",
            "Extreme Offset Red": "extreme_offset_red",
            "Specks Redscale": "specks_redscale",
            "Vintage": "vintage",
            "Perfume": "perfume",
            "Serenity": "serenity",
            "Eclectic": "eclectic",
            "Diagonal Lines": "diagonal_lines",
            "Green Specks": "green_specks",
            "Warmth": "warmth",
            "Casino": "casino",
            "Green Diagonal Lines": "green_diagonal_lines",
            "Offset": "offset",
            "Offset Blue": "offset_blue",
            "Neue": "neue",
            "Sunset": "sunset",
            "Specks": "specks",
            "Wood": "wood",
            "Lix": "lix",
            "Ryo": "ryo",
            "Bluescale": "bluescale",
            "Solange": "solange",
            "Evening": "evening",
            "Crimson": "crimson",
            "Teal Min Noise": "teal_min_noise",
            "Phase": "phase",
            "Dark Purple Min Noise": "dark_purple_min_noise",
            "Coral": "coral",
            "Darkify": "darkify",
            "Brightness": "incbrightness",
            "Brightness Second": "incbrightness2",
            "Yellow Casino": "yellow_casino",
            "Invert": "invert",
            "Saturation": "sat_adj",
            "Lemon": "lemon",
            "Pink Min Noise": "pink_min_noise",
            "Frontward": "frontward",
            "Pink Aura": "pink_aura",
            "Haze": "haze",
            "Cool Twilight": "cool_twilight",
            "Blues": "blues",
            "Mellow": "mellow",
            "Solange Dark": "solange_dark",
            "Solange Grey": "solange_grey",
            "Zapt": "zapt",
            "Eon": "eon",
            "Aeon": "aeon",
            "Matrix": "matrix",
            "Cosmic": "cosmic",
            "Min Noise": "min_noise",
            "Red Min Noise": "red_min_noise",
            "Matrix2": "matrix2",
            "Purplescale": "purplescale",
            "Radio": "radio",
            "Twenties": "twenties",
            "Pixel Blue": "pixel_blue",
            "Greyscale": "greyscale",
            "Grime": "grime",
            "Red Greyscale": "redgreyscale",
            "Retroviolet": "retroviolet",
            "Greengreyscale": "greengreyscale",
            "Green Med Noise": "green_med_noise",
            "Green Min Noise": "green_min_noise",
            "Blue Min Noise": "blue_min_noise",
            "Rosetint": "rosetint",
            "Purple Min Noise": "purple_min_noise",
            "Red Effect": "red_effect",
            "Gamma": "gamma",
            "Teal Gamma": "teal_gamma",
            "Purple Gamma": "purple_gamma",
            "Yellow Gamma": "yellow_gamma",
            "Bluered Gamma": "bluered_gamma",
            "Green Gamma": "green_gamma",
            "Red Gamma": "red_gamma",
            "Black Specks": "black_specks",
            "White Specks": "white_specks",
            "Salt and Pepper": "salt_and_pepper",
            "RGB Split": "rgbSplit",
            "Threshold": "threshold",
            "Threshold 75": "threshold75",
            "Threshold 125": "threshold125",
            "Pixelate": "pixelate",
            "Pixelate 16": "pixelate16"
        }
    }
}